### ISSUE TITLE
How to get the datasets?

### ISSUE THREAD

**Issue by lyhisme** [BenjaminFiltjens/MS-GCN#1]
Hi ,

Many thanks for sharing the code and I really like this interesting work. However, I can't find a link to download the corresponding dataset. How do I access the dataset?

Best regards

**Comment by BenjaminFiltjens** [comment]
Hi,

They would have to be acquired from the original data repositories:
LARa: https://zenodo.org/record/3862782#.YizNT3pKjZs
PKU-MMD: https://www.icst.pku.edu.cn/struct/Projects/PKUMMD.html
HuGaDB: https://github.com/romanchereshnev/HuGaDB
TUG: https://researchdata.ntu.edu.sg/dataset.xhtml?persistentId=doi:10.21979/N9/7VF22X
FOG: not public
