### ISSUE TITLE
Dataset Classes

### ISSUE THREAD

**Issue by MohammadBelalIrshaid** [BenjaminFiltjens/MS-GCN#11]
Hi, I just wanted to ask why the number of classes is set to be **2** in "**ms_gcn.py**" where all the datasets have classes varying from 5 to 52?

**Comment by BenjaminFiltjens** [comment]
Hi, that is just a placeholder. The number of classes is computed from main/data/mapping.txt. The toy example I provided to show how to structure datasets happens to have only 2 classes.
