### ISSUE TITLE
action segmentation in PKU_MMD

### ISSUE THREAD

**Issue by hitcbw** [BenjaminFiltjens/MS-GCN#3]
Hi Benjamin，
Thanks for your exciting efforts. I have modified the code to adjust to the dataset PKU_MMD with your help, thank you very much.  However,  i noticed that there exists action overlaps in PKU_MMD, e.g., several frames own double labels.
How does the MS-GCN work in this situation? As far as I know, the MS_TCN is a single-label classifier.

**Comment by BenjaminFiltjens** [comment]
Hi, you are correct. We only consider one class for the frames that have two output labels. If you want to know how we did this, I included an example label (from pku-mmd) and one generated by us.
[A01N01-L_output.csv
[A01N01-L.txt](https://github.com/BenjaminFiltjens/MS-GCN/files/8737981/A01N01-L.txt)
](https://github.com/BenjaminFiltjens/MS-GCN/files/8737976/A01N01-L_output.csv)

Also, transitions between two actions get class label 0 (even if it is only for 1 or 2 frames) and class 0 is one of the predicted output classes. Of course, better performance on PKU-MMD can be achieved by refining the labels and/or excluding transition periods. However, for a comparative study such as ours, the absolute performance on a given dataset is less relevant.
