### ISSUE TITLE
Dimension mismatch

### ISSUE THREAD

**Issue by Forgetmmmm** [BenjaminFiltjens/MS-GCN#4]
Hello,thanks for sharing the code.When I use the lara dataset,I encountered the following problem:
Training subject: 1
Traceback (most recent call last):
  File "/media/hz/A2/cmz/code/MS-GCN/main.py", line 68, in <module>
    trainer.train(model_dir, batch_gen, num_epochs=num_epochs, batch_size=bz, learning_rate=lr, device=device)
  File "/media/hz/A2/cmz/code/MS-GCN/model.py", line 36, in train
    batch_input, batch_target, mask, weight = batch_gen.next_batch(batch_size) 
  File "/media/hz/A2/cmz/code/MS-GCN/batch_gen.py", line 69, in next_batch
    batch_input_tensor[i, :, :np.shape(batch_input[i])[1], :, :] = torch.from_numpy(batch_input[i])
RuntimeError: The expanded size of the tensor (9) must match the existing size (19) at non-singleton dimension 2.  Target sizes: [6, 24000, 9, 1].  Tensor sizes: [12, 24000, 19, 1]
Do you know how to fix it?
Looking forward to your reply.

**Comment by BenjaminFiltjens** [comment]
Hi,
For each dataset you have to specify four settings:

- Ensure that the correct graph representation is chosen in ms_gcn (for lara: 'lara'). 
- Whether to use raw or relative features. For lara it is raw features, so comment out features = get_features(features) in batch_gen and model predict.
- Specify the correct sampling rate in main. For lara it is 50 hz, e.g. downsampling factor of 4.
- Specify the tensor dimensions in batch_gen. For lara there are 19 nodes. 

The error tells me that you did not set the last setting (i.e., in batch_gen change 9 to 19: batch_input_tensor = torch.zeros(len(batch_input), 6, max(length_of_sequences), 9, 1, dtype=torch.float).

**Comment by Forgetmmmm** [comment]
hello,could you tell me how to ensure that the correct graph representation is chosen in ms_gcn (for lara: 'lara')?I can't find the place to configure lara in ms_gcn.

**Comment by BenjaminFiltjens** [comment]
In ms-gcn line 30:
graph_args = {'layout': 'tp-vicon', 'strategy': 'spatial'}

Change 'tp-vicon' to the layout for a specific dataset, e.g., 'lara'.

**Comment by Forgetmmmm** [comment]
ok,thanks.
