### ISSUE TITLE
Lara Dataset

### ISSUE THREAD

**Issue by hitcbw** [BenjaminFiltjens/MS-GCN#6]
Hi benjamin,
Me here again :)  Another question haha!
I found the joint number of LARa is 39 referred to [LARa: Creating a Dataset for Human Activity Recognition in Logistics Using Semantic Attributes]. However, the norm_data_csv in OMoCap.zip (downloaded from your LARa link) owns 132/6 = 22 joints. Your report is 17 joints. It confused me a lot.
Did I made a mistake somewhere?

**Comment by BenjaminFiltjens** [comment]
Hi, we used the same number of nodes for LARA as we did for the TUG dataset (i.e., 19) (a mistake we corrected in the revised manuscript). The nodes were:
               ["root_RX", "root_RY", "root_RZ", "root_TX", "root_TY", "root_TZ",
               "R femur_RX", "R femur_RY", "R femur_RZ", "R femur_TX", "R femur_TY", "R femur_TZ",
               "R tibia_RX", "R tibia_RY", "R tibia_RZ", "R tibia_TX", "R tibia_TY", "R tibia_TZ",
               "R foot_RX", "R foot_RY", "R foot_RZ", "R foot_TX", "R foot_TY", "R foot_TZ",
               "R toe_RX", "R toe_RY", "R toe_RZ", "R toe_TX", "R toe_TY", "R toe_TZ",
               "L femur_RX", "L femur_RY", "L femur_RZ", "L femur_TX", "L femur_TY", "L femur_TZ",
               "L tibia_RX", "L tibia_RY", "L tibia_RZ", "L tibia_TX", "L tibia_TY", "L tibia_TZ",
               "L foot_RX", "L foot_RY", "L foot_RZ", "L foot_TX", "L foot_TY", "L foot_TZ",
               "L toe_RX", "L toe_RY", "L toe_RZ", "L toe_TX", "L toe_TY", "L toe_TZ",
               "lower back_RX", "lower back_RY", "lower back_RZ", "lower back_TX", "lower back_TY", "lower back_TZ",
               "head_RX", "head_RY", "head_RZ", "head_TX", "head_TY", "head_TZ",
               "R collar_RX", "R collar_RY", "R collar_RZ", "R collar_TX", "R collar_TY", "R collar_TZ",
               "R humerus_RX", "R humerus_RY", "R humerus_RZ", "R humerus_TX", "R humerus_TY", "R humerus_TZ",
               "R elbow_RX", "R elbow_RY", "R elbow_RZ", "R elbow_TX", "R elbow_TY", "R elbow_TZ",
               "R wrist_RX", "R wrist_RY", "R wrist_RZ", "R wrist_TX", "R wrist_TY", "R wrist_TZ",
               "L collar_RX", "L collar_RY", "L collar_RZ", "L collar_TX", "L collar_TY", "L collar_TZ",
               "L humerus_RX", "L humerus_RY", "L humerus_RZ", "L humerus_TX", "L humerus_TY", "L humerus_TZ",
               "L elbow_RX", "L elbow_RY", "L elbow_RZ", "L elbow_TX", "L elbow_TY", "L elbow_TZ",
               "L wrist_RX", "L wrist_RY", "L wrist_RZ", "L wrist_TX", "L wrist_TY", "L wrist_TZ"
               ]

Apologies for the confusion.

**Comment by hitcbw** [comment]
Thanks a lot :)
