### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by Forgetmmmm** [BenjaminFiltjens/MS-GCN#8]
Hello, sorry to bother you again, I would like to ask you why not to use the mainstream datasets such as breakfast, 50 salads, but with lara, hugadb?

**Comment by BenjaminFiltjens** [comment]
Those datasets are mainly benchmarks for RGB+flow-based action segmentation and not skeleton-based action segmentation.

**Comment by Forgetmmmm** [comment]
Thank you！
