### ISSUE TITLE
visiting phd

### ISSUE THREAD

**Issue by hitcbw** [BenjaminFiltjens/MS-GCN#9]
Hi Benjamin, I'm a ph.d candidate who has focused on human activity understanding for health care, especially for children with ASD (a neurodevelopmental disease and only can be intervened by behavioral tasks) for a long time. I'm interested in your and your team's work, but I can't find your email for further talking. Could your please leave your email here or send an email to chenbw@stu.hit.edu.cn ? Thanks a lot :)

**Comment by BenjaminFiltjens** [comment]
Hi Chen, you can find more info of my work (including contact information) at https://iiw.kuleuven.be/onderzoek/emedia/people/filtjensbenjamin 
My email is: benjamin.filtjens@kuleuven.be
